import lambda_handler as lh
environment= {'preload_list': [], 'preload_pending': [], 'scan_method': 'lambda', 'scan_uuid': 'cf42e333-638b-4270-af49-2ac232001a39', 'suffix_list': None, 'workers': 900}
options ={'_': { 'lambda_options': {'aws_profile': 'lambda', 'invoke_client': None, 'invoke_config': None, 'lambda_mode': False, 'lambda_session': None, 'logs_client': None, 'logs_config': None}, 'report_dir': '/opt/scan/pulse/data/./output/subdomains/scan', 'results_dir': '/opt/scan/pulse/data/./output/subdomains/scan/results'}, 'cache': False, 'debug': False, 'domains': '/opt/scan/pulse/data/./output/subdomains/gather/results/gathered.csv', 'lambda': False, 'lambda_profile': 'lambda', 'meta': False, 'output': '/opt/scan/pulse/data/./output/subdomains/scan', 'scan': 'pshtt,sslyze', 'serial': False, 'sort': True, 'workers': '900'}
#event = {'domain':'example.com','enviornment':{ '_': { 'lambda_options': {'aws_profile': 'lambda', 'invoke_client': None, 'invoke_config': None, 'lambda_mode': False, 'lambda_session': None, 'logs_client': None, 'logs_config': None}, 'report_dir': '/opt/scan/pulse/data/./output/subdomains/scan', 'results_dir': '/opt/scan/pulse/data/./output/subdomains/scan/results'}, 'cache': False, 'debug': False, 'domains': '/opt/scan/pulse/data/./output/subdomains/gather/results/gathered.csv', 'lambda': False, 'lambda_profile': 'lambda', 'meta': False, 'output': '/opt/scan/pulse/data/./output/subdomains/scan', 'scan': 'pshtt,sslyze', 'serial': False, 'sort': True, 'workers': '900'},'options' :{'_': { 'lambda_options': {'aws_profile': 'lambda', 'invoke_client': None, 'invoke_config': None, 'lambda_mode': False, 'lambda_session': None, 'logs_client': None, 'logs_config': None}, 'report_dir': '/opt/scan/pulse/data/./output/subdomains/scan', 'results_dir': '/opt/scan/pulse/data/./output/subdomains/scan/results'}, 'cache': False, 'debug': False, 'domains': '/opt/scan/pulse/data/./output/subdomains/gather/results/gathered.csv', 'lambda': False, 'lambda_profile': 'lambda', 'meta': False, 'output': '/opt/scan/pulse/data/./output/subdomains/scan', 'scan': 'pshtt,sslyze', 'serial': False, 'sort': True, 'workers': '900'}}
event ={'domain': 'gsa.gov', 'environment': {'suffix_list': None,'hosts_to_scan': [{'hostname': 'aboutusa.japan.usembassy.gov', 'port': 443, 'starttls_smtp': False}], 'scan_method': 'lambda', 'scan_uuid': 'fe913d5e-d4ce-474e-aace-657fa5899188', 'workers': 900}, 'options': {'sslyze_certs':False,'_': {'cache_dir': '/opt/scan/pulse/data/./output/subdomains/scan/cache', 'lambda_options': {'aws_profile': 'lambda', 'invoke_client': None, 'invoke_config': None, 'lambda_mode': True, 'lambda_session': None, 'logs_client': None, 'logs_config': None}, 'report_dir': '/opt/scan/pulse/data/./output/subdomains/scan', 'results_dir': '/opt/scan/pulse/data/./output/subdomains/scan/results'}, 'cache': False, 'debug': True, 'domains': '/opt/scan/pulse/data/./output/subdomains/gather/results/gathered.csv', 'lambda': False, 'lambda_profile': 'lambda', 'meta': True, 'output': '/opt/scan/pulse/data/./output/subdomains/scan', 'scan': 'pshtt,sslyze', 'serial': False, 'sort': True, 'workers': '900'}, 'scanner': 'sslyze'}
#en = {'hostname': 'example.com','scan_method': 'Local','suffix_list' : None}
#op = {'network_timeout' :100 ,'sslyze_certs':True}
#print(en.get('hostname'))
lh.main(event,'')
'''
enviornment = event.get('enviornment')
for i in enviornment.get('hosts_to_scan'):
    print(i.get('hostname'))
'''